---
output:
  pdf_document: default
  html_document: default
---

```{r echo=FALSE}
library(dplyr)
library(cluster)
library(pracma)
library(caret)
library(MASS)
library(ggplot2)
library(lattice)
library(grid)
library(DMwR)
library(readxl)
library(dendextend)
library(cluster)
library(factoextra)
library(ca)
library(FactoMineR)
library(nortest)
library(e1071)
library(pracma)
library(NbClust)

source("./ggbiplot.r")
source("./ggscreeplot.r")
```


```{r echo=TRUE}
# Defino funciones
sampleo <-function(dataset,split)
  {
    dni = 36637757
    n = round(split* nrow(dataset))
    set.seed(dni)
    mask = sample(1:nrow(dataset),size=n,replace=FALSE)
    dataset = dataset[mask,]
    return(dataset)
}

train_test <-function(dataset,split)
{
  dni = 36637757
  n = round(split* nrow(dataset))
  set.seed(dni)
  mask = sample(1:nrow(dataset),size=n,replace=FALSE)
  dataset_train = dataset[mask,]
  dataset_test = dataset[-mask,]
  return(list(dataset_train,dataset_test))
}

prostata_DataTypes <- function(dataset)
  {
    # elimino el id
    dataset = dataset[,-8]
    dataset = dataset[,-1] 
    # Seteo como factores
    dataset$CAPSULE = as.factor(dataset$CAPSULE)
    dataset$RACE = as.factor(dataset$RACE)
    dataset$DPROS = as.factor(dataset$DPROS)
    dataset$DCAPS = as.factor(dataset$DCAPS)
    
    # Seteo como numeros
    dataset$PSA = as.numeric(dataset$PSA)
    
    # Elimino filas con NA en gleason dado que hay errores en otros datos
    dataset = dataset[!is.na(dataset$GLEASON),]
    return(dataset)
}

seguros_Datatypes <- function(dataset)
{
  dataset$edad = as.numeric(dataset$edad)
  dataset$BMI= as.numeric(dataset$BMI)
  dataset$hijos= as.numeric(dataset$hijos)
  dataset$fuma= as.numeric(dataset$fuma)
  dataset$cargos= as.numeric(dataset$cargos)
  dataset$primadelseguro= as.numeric(dataset$primadelseguro)
  
  dataset$sexo = as.factor(dataset$sexo)
  dataset$region = as.factor(dataset$region)
  
  return(dataset)
  
}

```


```{r echo=TRUE}
prostata = read.csv(file ="./Prostata.csv",dec = ",")
prostata = sampleo(prostata,0.8)
prostata <- prostata_DataTypes(prostata) # Corrijo tipos de datos, elimino nulos,etc

nums <- unlist(lapply(prostata, is.numeric))
prostata_nums = prostata[,nums]
prostata_factor = prostata[,!nums]

prostata.train_test = train_test(prostata,split = 0.8)  # Dejo los dataset para clasificar no ingenuamente


```


```{r echo=TRUE}



par(mfcol = c(1,length(prostata_nums)))
for (k in 1:length(prostata_nums))
  {
    hist(prostata_nums[,k],proba = T,main = names(prostata_nums[,k]),10)
    x0 <- seq(min(prostata_nums[, k]), max(prostata_nums[, k]), le = 50) 
    lines(x0, dnorm(x0, mean(prostata_nums[,k]), sd(prostata_nums[,k])), col = "red", lwd = 2) 
    grid()
}

pval = list() 
par(mfcol = c(1,length(prostata_nums)))
for (k in 1:length(prostata_nums)){
  qqnorm(prostata_nums[,k],main = names(prostata_nums[k]))
  qqline(prostata_nums[,k],col="red") 
  pval[k] = ad.test(prostata_nums[,k])$p.value
  grid()
}
pval # Rechazo normalidad por en todas

cor(prostata_nums)

```


```{r echo=TRUE}
ggplot(data = prostata, mapping = aes(x = CAPSULE, y = PSA, colour = CAPSULE)) + 
  geom_boxplot() + theme_bw() + theme(legend.position =  "none")

ggplot(data = prostata, mapping = aes(x = CAPSULE, y = GLEASON, colour = CAPSULE)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = prostata, mapping = aes(x = CAPSULE, y = AGE, colour = CAPSULE)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")

xtabs(~CAPSULE+RACE, data=prostata)
xtabs(~CAPSULE+DPROS, data=prostata)  # Examen prostatico ( 1 no hay, 2 unico izq, 3 unico der ,4  ambos)
xtabs(~CAPSULE+DCAPS, data=prostata)  # deteccion de envoltura ( 1 si 2 no)

```


```{r echo=TRUE}
prostata_glm = glm(data = prostata.train_test[[1]], CAPSULE~., family = "binomial" )
summary(prostata_glm)

prostata.pred_test<-predict(prostata_glm,newdata=prostata.train_test[[2]], type="response") 
prostata.pred_test = ifelse(test=prostata.pred_test > 0.5,yes=1,no=0)
confusion_matrix=confusionMatrix(prostata.train_test[[2]]$CAPSULE,as.factor(prostata.pred_test))
confusion_matrix

```
```{r echo=TRUE}
# No deseable tener falsos negativos
prostata.pred_test<-predict(prostata_glm,newdata=prostata.train_test[[2]], type="response") 
prostata.pred_test = ifelse(test=prostata.pred_test > 0.10,yes=1, no=0)
confusion_matrix=confusionMatrix(as.factor(prostata.pred_test),prostata.train_test[[2]]$CAPSULE)
confusion_matrix

```
```{r echo=TRUE}
# Este algoritmo permite encontrar una fórmula más simple sin perder mucha bondad de clasificación

prostata_stepwise_glm <- prostata_glm %>%  stepAIC(trace=FALSE)
summary(prostata_stepwise_glm)

prostata.pred_test<-predict(prostata_stepwise_glm,newdata=prostata.train_test[[2]], type="response") 
prostata.pred_test = ifelse(test=prostata.pred_test > 0.11,yes=1,no=0)
confusion_matrix=confusionMatrix(as.factor(prostata.pred_test),prostata.train_test[[2]]$CAPSULE)
confusion_matrix

```


```{r echo=TRUE}
prostata_svm=svm(CAPSULE~ .,
              data=prostata.train_test[[1]],
              method="C-Classification",
              kernel="sigmoid",
              cost=100,
              gamma=1/nrow(prostata.train_test[[1]]))
svm_pred=predict(prostata_svm, newdata =  prostata.train_test[[2]])

confusion_matrix=confusionMatrix(as.factor(svm_pred),prostata.train_test[[2]]$CAPSULE)
confusion_matrix

```

```{r echo=TRUE}
prostata_test.numeric= prostata.train_test[[2]][,nums]
prostata_test.PCA = prcomp(prostata_test.numeric,center = TRUE, scale. = TRUE)
ggbiplot(prostata_test.PCA,obs.scale = 1,var.scale = 1,alpha = 0.5, groups = interaction(prostata.pred_test,prostata.train_test[[2]]$CAPSULE))

ggbiplot(prostata_test.PCA,obs.scale = 1,var.scale = 1,alpha = 0.5, groups = interaction(prostata.train_test[[2]]$CAPSULE))

ggbiplot(prostata_test.PCA,obs.scale = 1,var.scale = 1,alpha = 0.5, groups = interaction(prostata.pred_test))

```

```{r echo=TRUE}
seguros = read.csv(file = "./Seguros.csv", dec = ",")
seguros = sampleo(seguros,0.75)
seguros = seguros_Datatypes(seguros)
seguros = seguros[seguros$hijos < 300 & seguros$primadelseguro < 39000,]
nums <- unlist(lapply(seguros, is.numeric))
seguros.numeric = seguros[,nums]
seguros.factor = seguros[,!nums]
seguros.pca = prcomp(seguros.numeric,scale = TRUE)
ggbiplot(seguros.pca, obs.scale=1 ,var.scale=1, alpha=0.5,groups = as.factor(seguros$sexo) )
ggbiplot(seguros.pca, obs.scale=1 ,var.scale=1, alpha=0.5,groups = as.factor(seguros$region) )



```

```{r echo=TRUE}
boxplot(scale(seguros.numeric))

ggplot(data = seguros, mapping = aes( y = edad)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes( y = BMI)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes( y = hijos)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes( y = fuma)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes( y = cargos)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes( y = primadelseguro)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")

ggplot(data = seguros, mapping = aes(x = region, y = edad, colour = region)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes(x = sexo, y = edad, colour = sexo)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")

ggplot(data = seguros, mapping = aes(x = sexo, y = BMI, colour = sexo)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes(x = region, y = BMI, colour = region)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")

ggplot(data = seguros, mapping = aes(x = sexo, y = hijos, colour = sexo)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes(x = region, y = hijos, colour = region)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")

ggplot(data = seguros, mapping = aes(x = sexo, y = fuma, colour = sexo)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes(x = region, y = fuma, colour = region)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")

ggplot(data = seguros, mapping = aes(x = sexo, y = cargos, colour = sexo)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes(x = region, y = cargos, colour = region)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")

ggplot(data = seguros, mapping = aes(x = sexo, y = primadelseguro, colour = sexo)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")
ggplot(data = seguros, mapping = aes(x = region, y = primadelseguro, colour = region)) + 
  geom_boxplot() + theme_bw() + theme(legend.position = "none")



# Correlacion en las variables numricas
round(cor(seguros.numeric),2)
 



```

```{r echo=TRUE}
kmax = 10
seguros.pca = prcomp(seguros.numeric,scale = TRUE)

```


```{r echo=TRUE}
a= fviz_nbclust(scale(seguros.numeric),hcut,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="euclidean" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(a$data$y)
b= fviz_nbclust(scale(seguros.numeric),hcut,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="manhattan" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(b$data$y)
c= fviz_nbclust(scale(seguros.numeric),hcut,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="maximum" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(c$data$y)
d=fviz_nbclust(scale(seguros.numeric),hcut,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="minkowski" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(d$data$y)

```

```{r echo=TRUE}
a= fviz_nbclust(scale(seguros.numeric),kmeans,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="euclidean" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(a$data$y)
b= fviz_nbclust(scale(seguros.numeric),kmeans,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="manhattan" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(b$data$y)
c= fviz_nbclust(scale(seguros.numeric),kmeans,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="maximum" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(c$data$y)
d=fviz_nbclust(scale(seguros.numeric),kmeans,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="minkowski" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
max(d$data$y)

```

```{r echo=TRUE}
fviz_nbclust(scale(seguros.numeric),hcut,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="manhattan" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette
fviz_nbclust(scale(seguros.numeric),kmeans,method = c("silhouette"),nboot = 50,diss = dist(scale(seguros.numeric),method ="euclidean" )  ) # Elegimos 5 clusters por el critero de maximizar mean silhouette

```

```{r echo=TRUE}
mat_dist <- dist(x = scale(seguros.numeric), method = "manhattan") 
hc_complete <- hclust(d = mat_dist, method = "complete") 
hc_average  <- hclust(d = mat_dist, method = "average")
hc_single   <- hclust(d = mat_dist, method = "single")
hc_ward     <- hclust(d = mat_dist, method = "ward.D2")

```

```{r echo=TRUE}
plot(hc_complete )
rect.hclust(hc_complete, k=5, border="red")

plot(hc_average )
rect.hclust(hc_average, k=5, border="red")

plot(hc_single )
rect.hclust(hc_single, k=5, border="red")

plot(hc_ward )
rect.hclust(hc_ward, k=5, border="red")



```

```{r echo=TRUE}
seguros$hcluster<-cutree(hc_ward,k=5)#con 5 grupos
ggbiplot(seguros.pca, obs.scale=1 ,var.scale=1, alpha=0.5,groups = as.factor(seguros$hcluster) )

seguros %>%  mutate(region = as.numeric(seguros$region) -1) %>%  mutate(sexo = as.numeric(seguros$sexo)-1)%>% 
  group_by(hcluster) %>%
  summarise_all(mean) 

```


```{r echo=TRUE}
seguros.kmeans = kmeans(scale(seguros.numeric),nstart=50,centers = 5)
seguros$kmeanscluster = as.factor(seguros.kmeans$cluster)

ggbiplot(seguros.pca, obs.scale=1 ,var.scale=1, alpha=0.5,groups = as.factor(seguros$kmeansclust) )

seguros %>%  mutate(region = as.numeric(seguros$region) -1) %>%  mutate(sexo = as.numeric(seguros$sexo)-1)%>% 
  group_by(kmeanscluster) %>%
  summarise_all(mean) 

```


